### PR TITLE
Bugfix: Remove widgets from grid

### PR DESCRIPTION
**Pull request by kdietrich**
I fixed a small issue in your code. Any widget that gets deleted, now also gets removed from grid. Before this has led to several problems like auto positioning not working.

### CODE REVIEW

**Comment by mgwidmann** [comment]
:+1:

**Comment by mgwidmann** [comment]
I suspect there could be other data binding problems because of how this is done: https://github.com/Tropicalista/angular-gridstack/blob/master/src/angular-gridstack.js#L59

The observation only goes one way...

**Comment by Tropicalista** [comment]
With this fix widget will not be removed, accordingly to documentation: if false DOM node won't be removed from the tree (Optional. Default true).

**Comment by kdietrich** [comment]
@Tropicalista Nope. When you hit the Remove button, Angular removes the widget from scope and thus also from DOM. The remove_widget tells gridstack only to remove the widget from itself.

**Comment by Tropicalista** [comment]
Yes, it's what I want, remove completely from the dom. I think that leaving widget in the dom will decrease performance. Probably we should add a flag to enable/disable.

**Pull request closed without merging**
